# Generated by Django 4.1.6 on 2023-02-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reclapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='date_de_creation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
